### ISSUE TITLE
Pinyin "Not Available" in 5.0.14-1 

### ISSUE THREAD

**Issue by ShadiZade** [fcitx/fcitx5-chinese-addons#107] opened 2022-07-14 00:28 UTC
System: Manjaro Ruah

Problem:
Pinyin keyboard stopped working and started showing "Pinyin (Not Available)" when switching.

Solution: 
Downgrade to version 5.0.13-2.

**Comment by wengxt** [comment] 2022-07-14 00:35
Such error is usually due to packaging issue. It could happen when you only "partially" upgrade the system.

Since you're using manjaro, please update the whole system instead of only certain packages. Also 5.0.13 sounds very old, which seems to indicate you haven't update system for long time.

You might want to paste the output fcitx5-diagnose and we can then see what exact version of addons are installed.

Likely it's libime is not updated.

I'll close this because it's not upstream bug. But you can still post further comment for support.

**Closed by wengxt** 2022-07-14 00:35 UTC

**Comment by ShadiZade** [comment] 2022-07-16 13:10
This issue occurred immediately after a full system update.

**Comment by wengxt** [comment] 2022-07-16 13:28
but I need the version on your system to check. Can you run fcitx5-diagnose can paste the output?

and the output of
pacman -Qs fcitx5

 I think Manjaro should have 5.0.18 at least. I don’t know where this 5.0.14 version is from.

**Comment by wengxt** [comment] 2022-07-16 13:33
ah, I thought you mean fcitx5 version, sorry. but still, I would need to see the relevant package version on your system and in your repo.

can you run following command and paste the output of them?
```
pacman -Ss fcitx5
pacman -Si libime
fcitx5-diagnose
fcitx5 --verbose=*=5 -rd
```

**Comment by ShadiZade** [comment] 2022-07-16 14:21
```
pacman -Qs fcitx5

local/fcitx5-chinese-addons 5.0.13-2
    Addons related to Chinese, including IME previous bundled inside fcitx4
local/fcitx5-configtool 5.0.14-1 (fcitx5-im)
    Configuration Tool for Fcitx5
local/fcitx5-git 5.0.16.r0.g0aa13ce9-1
    Next generation of fcitx
local/fcitx5-gtk 5.0.16-1 (fcitx5-im)
    Fcitx5 gtk im module and glib based dbus client library
local/fcitx5-lua-git 5.0.8.r0.g072f1ed-1
    Lua support for fcitx5, with an imeapi addon implementing googlepinyin api
local/fcitx5-material-color 0.2.1-1
    Material color theme for fcitx5
local/fcitx5-qt5-git 5.0.12.r0.g3430f36-1
    Fcitx Qt Library, for Qt5
local/fcitx5-rime 5.0.14-1
    RIME support for Fcitx5

```
............
```
pacman -Ss fcitx5

community/fcitx5 5.0.18-2 (fcitx5-im)
    Next generation of fcitx
community/fcitx5-anthy 5.0.12-1
    Anthy Wrapper for Fcitx5
community/fcitx5-chewing 5.0.12-1
    Chewing Wrapper for Fcitx5
community/fcitx5-chinese-addons 5.0.14-1 [installed: 5.0.13-2]
    Addons related to Chinese, including IME previous bundled inside fcitx4
community/fcitx5-configtool 5.0.14-1 (fcitx5-im) [installed]
    Configuration Tool for Fcitx5
community/fcitx5-gtk 5.0.16-1 (fcitx5-im) [installed]
    Fcitx5 gtk im module and glib based dbus client library
community/fcitx5-hangul 5.0.10-1
    Hangul Wrapper for Fcitx5
community/fcitx5-kkc 5.0.10-1
    KKC Wrapper for Fcitx5
community/fcitx5-libthai 5.0.9-1
    Libthai Wrapper for Fcitx5
community/fcitx5-lua 5.0.9-1
    Lua support for Fcitx 5
community/fcitx5-m17n 5.0.10-1
    m17n Wrapper for Fcitx5
community/fcitx5-material-color 0.2.1-1 [installed]
    Material color theme for fcitx5
community/fcitx5-mozc 2.26.4632.102.g4d2e3bd-2
    Fcitx5 Module of A Japanese Input Method for Chromium OS, Windows, Mac and Linux (the Open Source Edition of Google Japanese Input)
community/fcitx5-nord 0.0.0.20210116-1
    Fcitx5 theme based on Nord color
community/fcitx5-pinyin-zhwiki 1:0.2.4.20220529-1
    Fcitx 5 Pinyin Dictionary from zh.wikipedia.org
community/fcitx5-qt 5.0.14-1 (fcitx5-im)
    Fcitx5 Qt Library
community/fcitx5-rime 5.0.14-1 [installed]
    RIME support for Fcitx5
community/fcitx5-sayura 5.0.8-1
    Sinhala Transe IME engine for Fcitx5
community/fcitx5-skk 5.0.13-1
    libskk wrapper for Fcitx5
community/fcitx5-table-extra 5.0.11-1
    Extra tables for Fcitx5
community/fcitx5-table-other 5.0.10-1
    Other tables for Fcitx5
community/fcitx5-unikey 5.0.11-1
    Unikey engine support for Fcitx5
community/manjaro-asian-input-support-fcitx5 2022.04-1
    Manjaro asian input support for fcitx5
community/ssfconv 1.1.1-1
    Sogou input method skin file (.ssf file) converter, supports conversion to fcitx or fcitx5 format

```

............

```
pacman -Si libime

Repository      : community
Name            : libime
Version         : 1.0.13-2
Description     : A library to support generic input method implementation
Architecture    : x86_64
URL             : https://github.com/fcitx/libime
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : boost-libs  fcitx5
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 28.20 MiB
Installed Size  : 51.74 MiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Mon 04 Jul 2022 04:42:08 AM EEST
Validated By    : MD5 Sum  SHA-256 Sum  Signature




```

............

```
fcitx5-diagnose

[...]

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.16`

3.  process:

    Found 1 fcitx5 process:

           5074 fcitx5
[...]

```
............
```
fcitx5 --verbose=*=5 -rd

zsh: no matches found: --verbose=*=5
```

**Comment by ShadiZade** [comment] 2022-07-16 14:23
By the way, an update to fcitx5-git arrived just today on the AUR. Maybe that's the issue? I added it to IgnorePkg because I didn't want it to break again.

**Comment by ShadiZade** [comment] 2022-07-16 14:25
Here are my update messages from pacman and yay:

```
sudo pacman -Syu

:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
warning: fcitx5-chinese-addons: ignoring package upgrade (5.0.13-2 => 5.0.14-1)
 there is nothing to do
```

............

```
yay -Sua

:: Searching AUR for updates...
 -> fcitx5-git: ignoring package upgrade (5.0.16.r0.g0aa13ce9-1 => 5.0.18.r13.g541a3e1-1)
 -> Flagged Out Of Date AUR Packages:  noto-fonts-sc
 there is nothing to do
```

**Comment by wengxt** [comment] 2022-07-16 14:25
Can you just try full system upgrade again and just use non-git version?

If you use "-git" and  forget to upgrade, then it will be eventually very out of date.

E.g. fcitx5-diagnose shows you only have 5.0.16 for fcitx5 package.

I don't see there's any reason to use fcitx5-git in your case.

**Comment by ShadiZade** [comment] 2022-07-16 14:29
Alright, so I tried to replace git with non-git. 

```
sudo pacman -S fcitx5

resolving dependencies...
looking for conflicting packages...
:: fcitx5 and fcitx5-git are in conflict. Remove fcitx5-git? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: removing fcitx5-git breaks dependency 'fcitx5-git' required by fcitx5-lua-git
:: removing fcitx5-git breaks dependency 'fcitx5-git' required by fcitx5-qt5-git
:: removing fcitx5-git breaks dependency 'fcitx5-git' required by libime-git
```

What do I do?

**Comment by wengxt** [comment] 2022-07-16 14:33
fcitx5 new release is cut about monthly, and only certain backwards compatibility is supported, because there can always be new API added in the new version, and new version may depending on new version of other packages. The only promise from upstream is that, if you put every version at the cut together, they should work.

Just replace everything with non -git, you even have lilbime-git and I think that is the root cause. 5.0.14 I believe uses some new API in libime

Mix -git and non-git is dangerous because if you don't manually upgrade -git package they will be out of date eventually.

**Comment by wengxt** [comment] 2022-07-16 14:35
Try install non-git version together in one pass.

```
pacman -S fcitx5 fcitx5-lua fcitx5-qt libime
```

**Comment by ShadiZade** [comment] 2022-07-16 14:40
Thanks! I just non-gitted everything and upgraded to the latest version, and it works perfectly. Here are the results for reference:

```
pacman -Qs fcitx5                                                                                                                                                                

local/fcitx5 5.0.18-2 (fcitx5-im)
    Next generation of fcitx
local/fcitx5-chinese-addons 5.0.14-1
    Addons related to Chinese, including IME previous bundled inside fcitx4
local/fcitx5-configtool 5.0.14-1 (fcitx5-im)
    Configuration Tool for Fcitx5
local/fcitx5-gtk 5.0.16-1 (fcitx5-im)
    Fcitx5 gtk im module and glib based dbus client library
local/fcitx5-lua 5.0.9-1
    Lua support for Fcitx 5
local/fcitx5-material-color 0.2.1-1
    Material color theme for fcitx5
local/fcitx5-qt 5.0.14-1 (fcitx5-im)
    Fcitx5 Qt Library
local/fcitx5-rime 5.0.14-1
    RIME support for Fcitx5

```

............

```
pacman -Ss fcitx5                                                                                                                                                                 

community/fcitx5 5.0.18-2 (fcitx5-im) [installed]
    Next generation of fcitx
community/fcitx5-anthy 5.0.12-1
    Anthy Wrapper for Fcitx5
community/fcitx5-chewing 5.0.12-1
    Chewing Wrapper for Fcitx5
community/fcitx5-chinese-addons 5.0.14-1 [installed]
    Addons related to Chinese, including IME previous bundled inside fcitx4
community/fcitx5-configtool 5.0.14-1 (fcitx5-im) [installed]
    Configuration Tool for Fcitx5
community/fcitx5-gtk 5.0.16-1 (fcitx5-im) [installed]
    Fcitx5 gtk im module and glib based dbus client library
community/fcitx5-hangul 5.0.10-1
    Hangul Wrapper for Fcitx5
community/fcitx5-kkc 5.0.10-1
    KKC Wrapper for Fcitx5
community/fcitx5-libthai 5.0.9-1
    Libthai Wrapper for Fcitx5
community/fcitx5-lua 5.0.9-1 [installed]
    Lua support for Fcitx 5
community/fcitx5-m17n 5.0.10-1
    m17n Wrapper for Fcitx5
community/fcitx5-material-color 0.2.1-1 [installed]
    Material color theme for fcitx5
community/fcitx5-mozc 2.26.4632.102.g4d2e3bd-2
    Fcitx5 Module of A Japanese Input Method for Chromium OS, Windows, Mac and Linux (the Open Source Edition of Google Japanese Input)
community/fcitx5-nord 0.0.0.20210116-1
    Fcitx5 theme based on Nord color
community/fcitx5-pinyin-zhwiki 1:0.2.4.20220529-1
    Fcitx 5 Pinyin Dictionary from zh.wikipedia.org
community/fcitx5-qt 5.0.14-1 (fcitx5-im) [installed]
    Fcitx5 Qt Library
community/fcitx5-rime 5.0.14-1 [installed]
    RIME support for Fcitx5
community/fcitx5-sayura 5.0.8-1
    Sinhala Transe IME engine for Fcitx5
community/fcitx5-skk 5.0.13-1
    libskk wrapper for Fcitx5
community/fcitx5-table-extra 5.0.11-1
    Extra tables for Fcitx5
community/fcitx5-table-other 5.0.10-1
    Other tables for Fcitx5
community/fcitx5-unikey 5.0.11-1
    Unikey engine support for Fcitx5
community/manjaro-asian-input-support-fcitx5 2022.04-1
    Manjaro asian input support for fcitx5
community/ssfconv 1.1.1-1
    Sogou input method skin file (.ssf file) converter, supports conversion to fcitx or fcitx5 format
```

............

```
pacman -Si libime                                                                                                                                                                

Repository      : community
Name            : libime
Version         : 1.0.13-2
Description     : A library to support generic input method implementation
Architecture    : x86_64
URL             : https://github.com/fcitx/libime
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : boost-libs  fcitx5
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 28.20 MiB
Installed Size  : 51.74 MiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Mon 04 Jul 2022 04:42:08 AM EEST
Validated By    : MD5 Sum  SHA-256 Sum  Signature


```

............

```
fcitx5-diagnose 

[...]

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.18`

3.  process:

    Found 1 fcitx5 process:

           5074 fcitx5

[...]
```
............

```
fcitx5 --verbose=*=5 -rd                                                                                                                                                  


zsh: no matches found: --verbose=*=5

```
